services:
  mongodb:
    image: mongo:latest
    container_name: dev_mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=dev
      - MONGO_INITDB_ROOT_PASSWORD=dev123
    ports:
      - "27017:27017"